id: ABD190737
title: Prayer to Karma Palden Khyentse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:12:53.051453
  last_modified_at: 2022-03-01 00:12:53.051460
